version: 2

sources:
  - name: raw
    schema: raw
    description: "Raw data hasil ingestion dari source system"

    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
      - name: payments